name: CI

on:
  push:
  pull_request:

jobs:
  build_and_check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      # Run pre-commit checks.
      - uses: pre-commit/action@v3.0.1
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y autoconf autogen automake bison \
            build-essential cmake libasound2-dev libboost-all-dev libbrotli-dev libbz2-dev \
            libcap-dev libdeflate-dev libflac-dev libharfbuzz-dev libjbig-dev libjpeg-dev \
            liblerc-dev liblcms2-dev liblzma-dev libmp3lame-dev libmpg123-dev libogg-dev \
            libopenjp2-7-dev libopus-dev libpam-dev libsqlite3-dev libssl-dev libtiff-dev libtool \
            libvorbis-dev libwebp-dev libxml2-dev libzstd-dev netcat-traditional pkg-config re2c \
            zip \
            && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y tclsh
      - name: Build all targets, all variants
        run: make --directory=./targets/ all
      - name: Verify build success
        run: make --question --directory=./targets/ all
